# Generated by Django 3.2.5 on 2021-12-22 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KeydabraManagerController', '0001_initial'),
        ('SummaryDXIInsightService', '0012_alter_collateral_reportid'),
        ('ClientManagementService', '0001_initial'),
        ('TransactionService', '0002_cnnrecommender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cnnrecommender',
            name='collateralID',
        ),
        migrations.RemoveField(
            model_name='cnnrecommender',
            name='parentImageID',
        ),
        migrations.RemoveField(
            model_name='cnnrecommender',
            name='productName',
        ),
        migrations.RemoveField(
            model_name='cnnrecommender',
            name='similarityScore',
        ),
        migrations.RemoveField(
            model_name='topproduct',
            name='productName',
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=100, null=True)),
                ('productDesc', models.CharField(max_length=500, null=True)),
                ('clientID', models.ForeignKey(db_column='clientID', on_delete=django.db.models.deletion.CASCADE, to='ClientManagementService.client')),
                ('collateralID', models.ForeignKey(db_column='collateralID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='SummaryDXIInsightService.collateral')),
            ],
            options={
                'db_table': 'Product',
            },
        ),
        migrations.CreateModel(
            name='CNNSimilarProduct',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('similarityScore', models.IntegerField(null=True)),
                ('recommendedProdID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendedProdID', to='TransactionService.product')),
                ('reportID', models.ForeignKey(db_column='reportID', on_delete=django.db.models.deletion.CASCADE, to='KeydabraManagerController.report')),
                ('sourceProdID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sourceProdID', to='TransactionService.product')),
            ],
            options={
                'db_table': 'CNNSimilarProduct',
            },
        ),
        migrations.AddField(
            model_name='cnnrecommender',
            name='productID',
            field=models.ForeignKey(db_column='productID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='TransactionService.product'),
        ),
        migrations.AddField(
            model_name='topproduct',
            name='productID',
            field=models.ForeignKey(db_column='productID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='TransactionService.product'),
        ),
    ]
