# Generated by Django 3.2.5 on 2021-12-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransactionService', '0003_auto_20211222_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cnnsimilarproduct',
            name='similarityScore',
            field=models.DecimalField(decimal_places=9, max_digits=10, null=True),
        ),
    ]
