# Generated by Django 3.2.5 on 2022-01-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransactionService', '0004_alter_cnnsimilarproduct_similarityscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productName',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
