# Generated by Django 3.2.5 on 2022-01-11 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TransactionService', '0005_alter_product_productname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionsummary',
            name='approvedBy',
        ),
        migrations.RemoveField(
            model_name='transactionsummary',
            name='isApproved',
        ),
    ]
