# Generated by Django 3.2.5 on 2022-03-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransactionService', '0006_auto_20220111_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionsummary',
            name='avgSizeOfPurchase',
            field=models.DecimalField(decimal_places=3, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='transactionsummary',
            name='income',
            field=models.DecimalField(decimal_places=3, max_digits=50, null=True),
        ),
    ]
