# Generated by Django 3.2.5 on 2022-03-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransactionService', '0007_auto_20220303_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cnnsimilarproduct',
            name='similarityScore',
            field=models.DecimalField(decimal_places=9, max_digits=50, null=True),
        ),
    ]
