# Generated by Django 3.2.5 on 2022-03-21 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KeydabraManagerController', '0004_auto_20220319_1532'),
        ('TransactionService', '0009_auto_20220319_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketBasket',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('confidenceScore', models.DecimalField(decimal_places=9, max_digits=50, null=True)),
                ('liftScore', models.DecimalField(decimal_places=9, max_digits=50, null=True)),
                ('totalPrice', models.DecimalField(decimal_places=9, max_digits=50, null=True)),
                ('combinationRank', models.IntegerField(null=True)),
                ('sortingOrder', models.CharField(max_length=20, null=True)),
                ('reportName', models.CharField(max_length=50)),
                ('antecedentProdID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='antecedentProdID', to='TransactionService.product')),
                ('consequentProdID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consequentProdID', to='TransactionService.product')),
                ('reportID', models.ForeignKey(db_column='reportID', on_delete=django.db.models.deletion.CASCADE, to='KeydabraManagerController.report')),
            ],
            options={
                'db_table': 'MarketBasket',
            },
        ),
    ]
