# Generated by Django 3.2.5 on 2021-09-02 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('roleName', models.CharField(max_length=20)),
                ('roleDescription', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'Role',
            },
        ),
        migrations.CreateModel(
            name='UserCredentials',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('userID', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('secretKey', models.CharField(max_length=30)),
                ('createdDate', models.DateTimeField(null=True)),
                ('updatedDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'UserCredentials',
            },
        ),
    ]
