# Generated by Django 3.2.5 on 2021-11-22 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KeydabraManagerController', '0001_initial'),
        ('VisualInsightService', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopFeature',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('featureName', models.CharField(max_length=100, null=True)),
                ('featureDescription', models.CharField(max_length=400, null=True)),
                ('featureOrderNumber', models.IntegerField(null=True)),
                ('significance', models.IntegerField(null=True)),
                ('isTopFeature', models.BooleanField(default=False)),
                ('algorithmName', models.CharField(max_length=100, null=True)),
                ('algorithmType', models.CharField(max_length=100, null=True)),
                ('reportID', models.ForeignKey(db_column='reportID', on_delete=django.db.models.deletion.CASCADE, to='KeydabraManagerController.report')),
            ],
            options={
                'db_table': 'TopFeature',
            },
        ),
    ]
