# Generated by Django 3.2.5 on 2021-11-27 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SummaryDXIInsightService', '0009_alter_statements_solutiontext'),
        ('VisualInsightService', '0002_topfeature'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('featureName', models.CharField(max_length=100, null=True)),
                ('featureDefinition', models.CharField(max_length=800, null=True)),
            ],
            options={
                'db_table': 'FeatureType',
            },
        ),
        migrations.RemoveField(
            model_name='topfeature',
            name='algorithmName',
        ),
        migrations.RemoveField(
            model_name='topfeature',
            name='algorithmType',
        ),
        migrations.RemoveField(
            model_name='topfeature',
            name='featureName',
        ),
        migrations.RemoveField(
            model_name='topfeature',
            name='featureOrderNumber',
        ),
        migrations.RemoveField(
            model_name='topfeature',
            name='isTopFeature',
        ),
        migrations.AddField(
            model_name='topfeature',
            name='clientSitePageID',
            field=models.ForeignKey(db_column='clientSitePageID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='VisualInsightService.clientsitepage'),
        ),
        migrations.AddField(
            model_name='topfeature',
            name='collateralID',
            field=models.ForeignKey(db_column='collateralID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='SummaryDXIInsightService.collateral'),
        ),
        migrations.AlterField(
            model_name='topfeature',
            name='featureDescription',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='topfeature',
            name='significance',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
