# Generated by Django 3.2.5 on 2021-11-27 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VisualInsightService', '0003_auto_20211127_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='topfeature',
            name='featureID',
            field=models.ForeignKey(db_column='featureID', default=2, on_delete=django.db.models.deletion.CASCADE, to='VisualInsightService.featuretype'),
        ),
    ]
