# Generated by Django 3.2.5 on 2022-01-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VisualInsightService', '0005_auto_20211130_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsitepage',
            name='pageReferenceID',
            field=models.IntegerField(null=True),
        ),
    ]
