# Generated by Django 3.2.5 on 2022-01-21 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VisualInsightService', '0007_alter_clientsitepage_updateddate'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureSuggestion',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('suggestionText', models.TextField(max_length=1000, null=True)),
                ('featureID', models.ForeignKey(db_column='featureID', on_delete=django.db.models.deletion.CASCADE, to='VisualInsightService.featuretype')),
            ],
            options={
                'db_table': 'FeatureSuggestion',
            },
        ),
    ]
