# Generated by Django 3.2.5 on 2022-01-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VisualInsightService', '0009_visitorsegmentation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorsegmentation',
            name='compositeDXI',
            field=models.DecimalField(decimal_places=15, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='visitorsegmentation',
            name='significance',
            field=models.DecimalField(decimal_places=7, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='visitorsegmentation',
            name='userID',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
