# Generated by Django 3.2.5 on 2022-03-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VisualInsightService', '0010_auto_20220125_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topfeature',
            name='significance',
            field=models.DecimalField(decimal_places=3, max_digits=50, null=True),
        ),
    ]
