# Generated by Django 3.2.5 on 2022-03-19 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VisualInsightService', '0012_auto_20220303_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerflow',
            name='reportName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='flowpageorder',
            name='reportName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='heatmap',
            name='reportName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='topfeature',
            name='reportName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visitorsegmentation',
            name='reportName',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
