# Generated by Django 3.2.5 on 2022-03-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VisualInsightService', '0013_auto_20220319_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerflow',
            name='reportName',
            field=models.CharField(default='ACDF', max_length=50),
        ),
        migrations.AlterField(
            model_name='flowpageorder',
            name='reportName',
            field=models.CharField(default='ACDF', max_length=50),
        ),
        migrations.AlterField(
            model_name='heatmap',
            name='reportName',
            field=models.CharField(default='ACDF', max_length=50),
        ),
        migrations.AlterField(
            model_name='topfeature',
            name='reportName',
            field=models.CharField(default='ACDF', max_length=50),
        ),
        migrations.AlterField(
            model_name='visitorsegmentation',
            name='reportName',
            field=models.CharField(default='ACDF', max_length=50),
        ),
    ]
