# Generated by Django 3.2.5 on 2022-05-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VisualInsightService', '0014_auto_20220319_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorsegmentation',
            name='userID',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
