# Generated by Django 3.2.5 on 2021-09-14 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SummaryDXIInsightService', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statements',
            name='referenceImage',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='statements',
            name='statementType',
            field=models.CharField(choices=[('INFER', 'Inference'), ('OBSER', 'Observation'), ('PRED', 'Prediction'), ('RECOM', 'Recommendation'), ('INSIGHT', 'Insight'), ('PRESC', 'Prescription')], max_length=10),
        ),
    ]
