# Generated by Django 3.2.5 on 2021-09-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SummaryDXIInsightService', '0002_auto_20210914_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statements',
            name='referenceImage',
        ),
        migrations.AlterField(
            model_name='statements',
            name='statementType',
            field=models.CharField(choices=[('INFER', 'Inference'), ('OBSER', 'Observation'), ('PRED', 'Prediction'), ('RECOM', 'Recommendation')], max_length=10),
        ),
    ]
