# Generated by Django 3.2.5 on 2021-09-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SummaryDXIInsightService', '0003_auto_20210921_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statements',
            name='statementType',
            field=models.CharField(choices=[('INFER', 'Inference'), ('OBSER', 'Observation'), ('PRED', 'Prediction'), ('RECOM', 'Recommendation'), ('INSIGHT', 'Insight'), ('PRESC', 'Prescription')], max_length=10),
        ),
    ]
