# Generated by Django 3.2.5 on 2021-10-07 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SummaryDXIInsightService', '0005_collateral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statements',
            name='statementType',
            field=models.CharField(choices=[('INFER', 'Inference'), ('OBSER', 'Observation'), ('PRED', 'Prediction'), ('RECOM', 'Recommendation'), ('INSIGHT', 'Insight'), ('PRESC', 'Prescription'), ('HEATMAP', 'Heatmap')], max_length=10),
        ),
    ]
