# Generated by Django 3.2.5 on 2021-11-24 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SummaryDXIInsightService', '0008_auto_20211120_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statements',
            name='solutionText',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
