# Generated by Django 3.2.5 on 2021-12-06 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SummaryDXIInsightService', '0009_alter_statements_solutiontext'),
    ]

    operations = [
        migrations.AddField(
            model_name='summaryinsights',
            name='bestSeller',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='summaryinsights',
            name='bestSource',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
