# Generated by Django 3.2.5 on 2021-12-21 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KeydabraManagerController', '0001_initial'),
        ('SummaryDXIInsightService', '0011_summaryinsights_allappdownloads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collateral',
            name='reportID',
            field=models.ForeignKey(db_column='reportID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='KeydabraManagerController.report'),
        ),
    ]
