# Generated by Django 3.2.5 on 2022-01-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SummaryDXIInsightService', '0012_alter_collateral_reportid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collateral',
            name='typeName',
            field=models.TextField(max_length=350, null=True),
        ),
    ]
