# Generated by Django 3.2.5 on 2022-03-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SummaryDXIInsightService', '0013_alter_collateral_typename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summaryinsights',
            name='BehavioralDXI',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='summaryinsights',
            name='DXI',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='summaryinsights',
            name='GAConversionRate',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='summaryinsights',
            name='KPIDXI',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='summaryinsights',
            name='TargetDXI',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='summaryinsights',
            name='TransactionalDXI',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='summaryinsights',
            name='VisualDXI',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='summaryinsights',
            name='currentConversionRate',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='summaryinsights',
            name='lowDXIConversionRate',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='summaryinsights',
            name='netDollarValue',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='summaryinsights',
            name='targetConversionRate',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='summaryinsights',
            name='topDXIConversionRate',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='summaryinsights',
            name='transactions',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
    ]
