# Generated by Django 3.2.5 on 2022-03-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SummaryDXIInsightService', '0014_auto_20220303_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='collateral',
            name='collateralName',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
