# Generated by Django 3.2.5 on 2022-03-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SummaryDXIInsightService', '0015_collateral_collateralname'),
    ]

    operations = [
        migrations.AddField(
            model_name='statements',
            name='reportName',
            field=models.CharField(default='ACDF', max_length=50),
        ),
        migrations.AddField(
            model_name='summaryinsights',
            name='reportName',
            field=models.CharField(default='ACDF', max_length=50),
        ),
    ]
