# Generated by Django 3.2.5 on 2022-03-21 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SummaryDXIInsightService', '0016_auto_20220319_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='collateral',
            name='reportName',
            field=models.CharField(default='ACDF', max_length=50),
        ),
    ]
