# Generated by Django 3.2.5 on 2022-04-07 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SummaryDXIInsightService', '0017_collateral_reportname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collateral',
            name='reportName',
        ),
    ]
