# Generated by Django 3.2.5 on 2021-09-02 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('KeydabraAdminController', '0001_initial'),
        ('ClientManagementService', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('fromPeriod', models.DateField()),
                ('toPeriod', models.DateField()),
                ('forMonth', models.CharField(max_length=15)),
                ('isApproved', models.BooleanField(null=True)),
                ('isQADone', models.BooleanField(null=True)),
                ('createdDate', models.DateField(null=True)),
                ('updatedDate', models.DateField(auto_now_add=True)),
                ('approvedDate', models.DateField(null=True)),
                ('approvedBy', models.ForeignKey(db_column='approvedBy', on_delete=django.db.models.deletion.CASCADE, to='ClientManagementService.clientuser')),
                ('clientID', models.ForeignKey(db_column='clientID', on_delete=django.db.models.deletion.CASCADE, to='ClientManagementService.client')),
                ('reportPreparedBy', models.ForeignKey(db_column='reportPreparedBy', on_delete=django.db.models.deletion.CASCADE, to='KeydabraAdminController.keydabrauser')),
            ],
            options={
                'db_table': 'Report',
            },
        ),
    ]
