# Generated by Django 3.2.5 on 2022-01-04 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ClientManagementService', '0001_initial'),
        ('KeydabraManagerController', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientReportSchedule',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('deliveryDate', models.DateField(null=True)),
                ('draftDate', models.DateField(null=True)),
                ('publishDate', models.DateField(null=True)),
                ('clientID', models.ForeignKey(db_column='clientID', on_delete=django.db.models.deletion.CASCADE, to='ClientManagementService.client')),
            ],
            options={
                'db_table': 'ClientReportSchedule',
            },
        ),
    ]
