# Generated by Django 3.2.5 on 2022-01-08 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KeydabraManagerController', '0002_clientreportschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='approvedBy',
        ),
        migrations.RemoveField(
            model_name='report',
            name='reportPreparedBy',
        ),
    ]
