# Generated by Django 3.2.5 on 2021-12-29 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagementService', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='password123', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='secretKey',
            field=models.CharField(default='secretKey1234', max_length=30),
        ),
    ]
