# Generated by Django 3.2.5 on 2022-02-18 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagementService', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isDevelopment',
            field=models.BooleanField(default=False),
        ),
    ]
