# Generated by Django 3.2.5 on 2021-09-14 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('KeydabraManagerController', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyDataType',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('typeName', models.CharField(max_length=20)),
                ('typeDescripption', models.CharField(max_length=35)),
            ],
            options={
                'db_table': 'KeyDataType',
            },
        ),
        migrations.CreateModel(
            name='KeyData',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('userCount', models.IntegerField(null=True)),
                ('revenue', models.DecimalField(decimal_places=3, max_digits=10)),
                ('conversionRate', models.DecimalField(decimal_places=3, max_digits=10)),
                ('isApproved', models.BooleanField(null=True)),
                ('approvedBy', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=35)),
                ('keyDataTypeID', models.ForeignKey(db_column='keyDataTypeID', on_delete=django.db.models.deletion.CASCADE, to='KeyDataService.keydatatype')),
                ('reportID', models.ForeignKey(db_column='reportID', on_delete=django.db.models.deletion.CASCADE, to='KeydabraManagerController.report')),
            ],
            options={
                'db_table': 'KeyData',
            },
        ),
        migrations.CreateModel(
            name='GoogleAnalyticsData',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('parameterName', models.CharField(max_length=50)),
                ('keyHeader', models.CharField(max_length=35, null=True)),
                ('valueHeader', models.CharField(max_length=35, null=True)),
                ('key', models.CharField(max_length=50, null=True)),
                ('value', models.CharField(max_length=50, null=True)),
                ('isApproved', models.BooleanField(null=True)),
                ('approvedBy', models.CharField(max_length=50, null=True)),
                ('reportID', models.ForeignKey(db_column='reportID', on_delete=django.db.models.deletion.CASCADE, to='KeydabraManagerController.report')),
            ],
            options={
                'db_table': 'GoogleAnalyticsData',
            },
        ),
    ]
