# Generated by Django 3.2.5 on 2021-10-16 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KeyDataService', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keydata',
            name='approvedBy',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='keydata',
            name='conversionRate',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='keydata',
            name='revenue',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
    ]
