# Generated by Django 3.2.5 on 2021-12-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KeyDataService', '0003_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='countryCode',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
