# Generated by Django 3.2.5 on 2022-01-19 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KeydabraManagerController', '0003_auto_20220108_0542'),
        ('KeyDataService', '0004_location_countrycode'),
    ]

    operations = [
        migrations.CreateModel(
            name='SegmentationData',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('segmentType', models.CharField(max_length=35, null=True)),
                ('loosingScore', models.IntegerField(null=True)),
                ('loyalScore', models.IntegerField(null=True)),
                ('hibernatingScore', models.IntegerField(null=True)),
                ('topScore', models.IntegerField(null=True)),
                ('reportID', models.ForeignKey(db_column='reportID', on_delete=django.db.models.deletion.CASCADE, to='KeydabraManagerController.report')),
            ],
            options={
                'db_table': 'SegmentationData',
            },
        ),
    ]
