# Generated by Django 3.2.5 on 2022-03-19 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KeyDataService', '0005_segmentationdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='keydata',
            name='reportName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='segmentationdata',
            name='reportName',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
