# Generated by Django 3.2.5 on 2022-03-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KeyDataService', '0006_auto_20220319_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keydata',
            name='reportName',
            field=models.CharField(default='ACDF', max_length=50),
        ),
        migrations.AlterField(
            model_name='segmentationdata',
            name='reportName',
            field=models.CharField(default='ACDF', max_length=50),
        ),
    ]
