# Generated by Django 3.2.5 on 2021-10-23 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('KeydabraManagerController', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordCloud',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(max_length=1000, null=True)),
                ('frequency', models.IntegerField(null=True)),
                ('reportID', models.ForeignKey(db_column='reportID', on_delete=django.db.models.deletion.CASCADE, to='KeydabraManagerController.report')),
            ],
            options={
                'db_table': 'WordCloud',
            },
        ),
        migrations.CreateModel(
            name='ReviewSentiment',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('positiveScore', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('negativeScore', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('neutralScore', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('reportID', models.ForeignKey(db_column='reportID', on_delete=django.db.models.deletion.CASCADE, to='KeydabraManagerController.report')),
            ],
            options={
                'db_table': 'ReviewSentiment',
            },
        ),
    ]
