# Generated by Django 3.2.5 on 2021-10-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BehavioralInsightService', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordcloud',
            name='frequency',
        ),
        migrations.AddField(
            model_name='wordcloud',
            name='metaInfo',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='wordcloud',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
