# Generated by Django 3.2.5 on 2021-10-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BehavioralInsightService', '0002_auto_20211028_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordcloud',
            name='frequency',
            field=models.IntegerField(null=True),
        ),
    ]
