# Generated by Django 3.2.5 on 2022-01-19 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KeydabraManagerController', '0003_auto_20220108_0542'),
        ('KeyDataService', '0004_location_countrycode'),
        ('BehavioralInsightService', '0003_wordcloud_frequency'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterData',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('sliceName', models.CharField(max_length=50, null=True)),
                ('sliceScore', models.IntegerField(null=True)),
                ('keyDataTypeID', models.ForeignKey(db_column='keyDataTypeID', on_delete=django.db.models.deletion.CASCADE, to='KeyDataService.keydatatype')),
                ('reportID', models.ForeignKey(db_column='reportID', on_delete=django.db.models.deletion.CASCADE, to='KeydabraManagerController.report')),
            ],
            options={
                'db_table': 'ClusterData',
            },
        ),
    ]
