# Generated by Django 3.2.5 on 2022-03-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BehavioralInsightService', '0006_auto_20220119_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clusterdata',
            name='score',
            field=models.DecimalField(decimal_places=3, max_digits=50, null=True),
        ),
    ]
