# Generated by Django 3.2.5 on 2022-03-19 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BehavioralInsightService', '0008_auto_20220319_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clusterdata',
            name='reportName',
            field=models.CharField(default='ACDF', max_length=50),
        ),
        migrations.AlterField(
            model_name='reviewsentiment',
            name='reportName',
            field=models.CharField(default='ACDF', max_length=50),
        ),
        migrations.AlterField(
            model_name='wordcloud',
            name='reportName',
            field=models.CharField(default='ACDF', max_length=50),
        ),
    ]
