# Generated by Django 3.2.5 on 2022-01-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientManagementService', '0002_client_companyid'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='isLite',
            field=models.BooleanField(default=False),
        ),
    ]
