# Generated by Django 3.2.5 on 2022-01-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientManagementService', '0003_client_islite'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='isPro',
            field=models.BooleanField(default=False),
        ),
    ]
