# Generated by Django 3.2.5 on 2022-05-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientManagementService', '0004_client_ispro'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='subscription',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
