# Generated by Django 3.2.5 on 2021-11-08 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SummaryDXIInsightService', '0007_auto_20211020_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('prescriptionName', models.TextField(null=True)),
                ('prescriptionSection', models.CharField(max_length=25, null=True)),
                ('prescriptionText', models.TextField(null=True)),
                ('implementaionDate', models.DateField(null=True)),
                ('implementationStatus', models.BooleanField(default=False)),
                ('predictionID', models.ForeignKey(db_column='predictionID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='SummaryDXIInsightService.statements')),
            ],
            options={
                'db_table': 'Prescription',
            },
        ),
    ]
