# Generated by Django 3.2.5 on 2021-11-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrescriptionService', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='reportForMonth',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
